language: go

go:
  - 1.8

install:
- go get -u github.com/rwcarlsen/goexif/exif
- go get -u github.com/disintegration/gift
- go get -u github.com/olebedev/config
- go get -u github.com/mitchellh/mapstructure 

